test:
  filter_chain:
    #- name: shadows
    #  type: ScanShadowsFilter
    #  params:
    #    min_angle: 5
    #    max_angle: 175
    #    neighbors: 20
    #    window: 1
    - name: intensities
      type: LaserScanIntensityFilter
      params:
        lower_threshold: 931
        upper_threshold: 2000
        disp_histogram: 0
